language: python
os: linux
dist: xenial

services:
  - docker

python:
  - '3.9'

install:
  - sudo apt-get update
  - sudo apt-get install -yq --assume-yes --no-install-recommends gcc wget
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - pip install -r examples/requirements.txt
  - pip install -e ".[tests]"

script:
  - pytest

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5d585e560cb2e7b4fe45
    on_success: change
    on_failure: always
    on_start: never
